linters:
  disable:
    - structcheck # doesn't support Go 1.18 yet

    # I don't have a good reason for disabling these, other than that
    # they currently don't pass.
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - varcheck
  enable:
    - gofmt
